import type { IconType } from "react-icons";
import {
  SiApollographql,
  SiAxios,
  SiDjango,
  SiExpress,
  SiFigma,
  SiFilezilla,
  SiGit,
  SiGithub,
  SiGraphql,
  SiJavascript,
  SiJsonwebtokens,
  SiMongodb,
  SiMongoose,
  SiMui,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiPostman,
  SiReact,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiSocketdotio,
  SiSwiper,
  SiTypescript,
  SiYarn,
} from "react-icons/si";
import {
  TbAlertSquareRounded,
  TbCookie,
  TbForms,
  TbKey,
  TbLayersSubtract,
  TbLock,
  TbPencil,
  TbPlugConnected,
  TbServer2,
  TbShieldLock,
  TbUpload,
  TbVersions,
  TbWaveSine,
  TbWorldWww,
} from "react-icons/tb";

export const TECH_ICONS: Record<string, IconType> = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  react: SiReact,
  next: SiNextdotjs,
  redux: SiRedux,
  query: SiReactquery,
  mui: SiMui,
  socket: TbPlugConnected,
  axios: SiAxios,
  sweet: TbAlertSquareRounded,
  anime: TbWaveSine,
  tui: TbPencil,
  graphql: SiGraphql,
  apollo: SiApollographql,
  swiper: SiSwiper,
  node: SiNodedotjs,
  express: SiExpress,
  nest: SiNestjs,
  mongodb: SiMongodb,
  mongoose: SiMongoose,
  redis: SiRedis,
  multer: TbUpload,
  form: TbForms,
  cookie: TbCookie,
  bcrypt: TbLock,
  jwt: SiJsonwebtokens,
  socketio: SiSocketdotio,
  mvc: TbLayersSubtract,
  session: TbKey,
  django: SiDjango,
  postman: SiPostman,
  yarn: SiYarn,
  nvm: TbVersions,
  npm: SiNpm,
  git: SiGit,
  filezilla: SiFilezilla,
  github: SiGithub,
  figma: SiFigma,
  dns: TbWorldWww,
  firewall: TbShieldLock,
  vps: TbServer2,
};

export const TECH_ICON_KEYS = Object.keys(TECH_ICONS);
